name: Log ISS Location Data Daily

on:
  schedule:
    # Runs at 10:57 UTC (morning) every day
    - cron: "50 21 * * *"
  workflow_dispatch: # Allows manual triggering

jobs:
  collect-iss-data:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: 23f3002138@ds.study.iitm.ac.in
        run: echo "I am yaswanth"
        
     
     
